services:
  - type: web
    name: quiz-lgpd-belz
    runtime: python3
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
